/**
 * Generated by typeshare 1.13.3
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class ScanAddressTarget (
	val assetId: AssetId,
	val address: String
)

@Serializable
data class ScanTransaction (
	val isMalicious: Boolean,
	val isMemoRequired: Boolean
)

@Serializable
data class ScanTransactionPayload (
	val origin: ScanAddressTarget,
	val target: ScanAddressTarget,
	val website: String? = null,
	val type: TransactionType
)

@Serializable
enum class AddressType(val string: String) {
	@SerialName("address")
	Address("address"),
	@SerialName("contract")
	Contract("contract"),
	@SerialName("validator")
	Validator("validator"),
	@SerialName("contact")
	Contact("contact"),
	@SerialName("internalWallet")
	InternalWallet("internalWallet"),
}

